version: 0.0               # Specifies the version number of the file format.
os: linux                  # Specifies the operating system to be used.

files:                     # Defines files to be copied from source to destination.
  - source: /              # Source directory.
    destination: /var/www/html # Destination directory where files will be copied.

hooks:                     # Defines scripts to be executed at different deployment stages.
  AfterInstall:            # Executes a script after the installation of the application.
    - location: scripts/install_nginx.sh  # Path to the script file.
      timeout: 300         # Maximum time (in seconds) for the script to run.
      runas: root          # User to execute the script.

  ApplicationStart:        # Executes a script after the application has started.
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
