version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - sudo yum update -y
      - sudo yum install nginx -y

  build:
    commands:
      - echo "Build started on $(date)"
      - sudo mkdir -p /var/www/html
      - sudo cp index.html /var/www/html/

  post_build:
    commands:
      - echo "Configuring NGINX"

artifacts:
  files:
    - /var/www/html/index.html
